# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Home-ARM

stages:
- stage: Build
  displayName: Build ${{ variables.app_language }} image
  jobs:  
  - job: DockerImageBuild
    displayName: Build and push Docker image
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'docker-hub'
          repository: '$(docker_repo)'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          buildContext: '.'
          tags: 'rpi-$(Build.BuildId)'

- stage: DevDeployment
  displayName: Dev Deployment
  jobs:
    - job: PrepareDeployment
      displayName: Prepare k8s deployment file
      steps:
      - template: templates/deployment.yaml   
        parameters:
          database_host: 'postgres.database'
          database_port: '5432'
          database_name: 'trainer_panel.db'
