# Dockerfile.rails
FROM ruby:alpine3.13 AS rails-toolbox

ARG USER_ID
ARG GROUP_ID

RUN adduser --disabled-password --gecos '' --uid $USER_ID user

ENV INSTALL_PATH /opt/app
RUN mkdir -p $INSTALL_PATH

RUN apk add --no-cache build-base
RUN gem install rails bundler
RUN chown -R user:user $INSTALL_PATH
WORKDIR $INSTALL_PATH

USER $USER_ID
CMD ["/bin/sh"]