apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: v1
kind: Secret
metadata:
  name: tp-db-secret
  namespace: database
type: Opaque
data:
  POSTGRES_USER: <USER>
  POSTGRES_PASSWORD: <PASSWORD>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: database
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:10.4
        env:
          - name: POSTGRES_DB
            value: trainer_panel.db
        envFrom:
          - secretRef:
              name: tp-db-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb
        ports:
        - containerPort: 5432
      volumes:
        - name: postgredb
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: database
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432