parameters:
    database_port: ''
    docker_repo: 'wotd/trainer-panel'
    database_name: ''
    database_host: ''


steps:
- script: |
    export DATABASE_HOST=${{ parameters.database_host }}
    export DATABASE_PORT=${{ parameters.database_port }}
    export DATABASE_NAME=${{ parameters.database_name }}
    export APP_NAME=trainer-panel
    export NAMESPACE=ns-${APP_NAME}
    export CONTAINER_IMAGE=$(docker_repo):$(Build.BuildId)
    
    envsubst < k8s-deployments/application_template.yaml > k8s-deployments/tp.yaml
    kubectl apply -f k8s-deployments/tp.yaml
- publish: k8s-deployments/tp.yaml
  artifact: TPDeployment
